"""modifying Forum's attribute for replied_at as Nullable

Revision ID: 4cae0e421ad4
Revises: 774d21eff2f3
Create Date: 2024-10-12 20:20:29.165531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cae0e421ad4'
down_revision = '774d21eff2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum', schema=None) as batch_op:
        batch_op.alter_column('replied_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum', schema=None) as batch_op:
        batch_op.alter_column('replied_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
