"""modifying Forum's attribute for answer as Nullable

Revision ID: 774d21eff2f3
Revises: 8160d3b3ad5e
Create Date: 2024-10-12 20:18:41.277570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '774d21eff2f3'
down_revision = '8160d3b3ad5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
