"""modifying attribute (question, answer) in Forum model

Revision ID: 8160d3b3ad5e
Revises: a3a7ac0af004
Create Date: 2024-10-12 18:01:49.345998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8160d3b3ad5e'
down_revision = 'a3a7ac0af004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('answer', sa.Text(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=False))
        batch_op.drop_column('answer')
        batch_op.drop_column('question')

    # ### end Alembic commands ###
