"""adding is_drafted attribute to Artikel's Model

Revision ID: 8cc6b9ceb491
Revises: 
Create Date: 2024-10-11 20:22:06.686211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc6b9ceb491'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_drafted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.drop_column('is_drafted')

    # ### end Alembic commands ###
