"""adding is_approved as status attribute for Artikel's model

Revision ID: a3a7ac0af004
Revises: 8cc6b9ceb491
Create Date: 2024-10-12 17:57:08.781435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a7ac0af004'
down_revision = '8cc6b9ceb491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
